#!/bin/bash
############################################################
# Developed by Store-Host
# Version 0.0.5.0
# Web: https://www.store-host.com
#       Store-Host is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
############################################################
. /usr/share/mocis/sys/config/setup-vars
source $Path/repo/apt/9/installation
lamp_php7=0
gitlab=0
pve=0
do_pvegw=0
lamp_interactive=0
docker=0
goback=0
nginx=0
do_nfs_server=0
omv=0
apache2=0
mysql=0
mariadb=0
openvpn=0
hostname=0
wordpress=0
INPUT=sh-installer.sh.$$

dialog --clear --backtitle "[ M.O.C.I.S ]" \
--title "[ Installation menu ]" \
--no-lines \
--menu "You can Install Apache, PHP, MySQL, and much more." 0 0 9 \
Apache "Webserver" \
Gitlab "Gitlab" \
Lamp-PHP7 "PHP, MySQL, Apache" \
Lamp-Interactive "Choose what you want" \
MySQL "SQL Server" \
MariaDB "SQL Server" \
Nginx "Webserver" \
NFS-Server "Network storage" \
Openmediavault "Network storage" \
OpenVPN "Angristan installer" \
Proxmox "Virtual Server Hosting" \
PVEMail "Proxmox Mail Gateway" \
Wordpress "Blog CMS" \
Back "Back to the Main Menu" \
Exit "Exit to the shell" 2>"${INPUT}"
menuitem=$(<"${INPUT}")
[ -f $INPUT ] && rm $INPUT
case $menuitem in
        Apache) apache2=1;;
        Gitlab) gitlab=1;;
        Lamp-PHP7) lamp_php7=1;;
        Lamp-Interactive) lamp_interactive=1;;
        MySQL) mysql=1;;
        MariaDB) mariadb=1;;
        Nginx) nginx=1;;
        NFS-Server) do_nfs_server=1;;
        Openmediavault) omv=1;;
        OpenVPN) openvpn=1;;
        Proxmox) pve=1;;
        PVEMail) do_pvegw=1;;
        Wordpress) wordpress=1;;
		    Back) goback=1;;
        Exit) echo "Bye"; clear;;
esac
if [ $lamp_php7 = 1 ] ; then
			dialog --yesno "This can damage your system !! Do you want to continue?" 0 0
		response=$?
		case $response in
		0) echo "Starte";;
		1) echo exit;;
		255) echo "[ESC] key pressed.";;
		esac
			if [ $response = 0 ]
			then
				if cat /etc/issue.net | grep 9; then
					chmod -+x $Path/repo/apt/9/LAMP-PHP7.deb9.pl
					perl $Path/repo/apt/9/LAMP-PHP7.deb9.pl
				else
					chmod -+x $Path/repo/apt/8/LAMP-PHP7.deb.pl
					perl $Path/repo/apt/8/LAMP-PHP7.deb.pl
				fi
			fi
fi
if [ $pve = 1 ] ; then
  dialog --title "Agreement" \
  --backtitle "Mocis.sh" \
  --no-lines \
  --yesno "Are you sure, you want to install Proxmox Virual Server Providing?  " 0 0
  response=$?
          case $response in
          0) echo "starting";;
          1) bash $Home;;
          255) clear echo "[ESC] key pressed.";;
  		esac
  			if [ $response = 0 ]
  			then
          proxmoxhyper start_pvehyper
          goback=1
        fi
fi
if [ $do_pvegw = 1 ]; then
  dialog --title "Agreement" \
  --backtitle "Mocis.sh" \
  --no-lines \
  --yesno "Are you sure, you want to install Proxmox Mail Gateway?  " 0 0
  response=$?
          case $response in
          0) echo "starting";;
          1) bash $Home;;
          255) clear echo "[ESC] key pressed.";;
      esac
        if [ $response = 0 ]
        then
          proxmoxmailgw start_pvegw
          goback=1
        fi
fi
if [ $wordpress = 1 ] ; then
  dialog --title "Agreement" \
  --backtitle "Mocis.sh" \
  --no-lines \
  --yesno "Are you sure, you want to install Wordpress?  " 0 0
  response=$?
          case $response in
          0) echo "starting";;
          1) bash $Home;;
          255) clear echo "[ESC] key pressed.";;
  		esac
  			if [ $response = 0 ]
  			then
          F_wordpress start_wpinstall
          goback=1
        fi
fi
if [ $gitlab = 1 ]; then
  dialog --title "Agreement" \
  --backtitle "Mocis.sh" \
  --no-lines \
  --yesno "Are you sure, you want to install Gitlab?  " 0 0
  response=$?
          case $response in
          0) echo "starting";;
          1) bash $Home;;
          255) clear echo "[ESC] key pressed.";;
      esac
        if [ $response = 0 ]
        then
          F_gitlab start_gitlab
          goback=1
        fi
fi
if [ $do_nfs_server = 1 ]; then
  dialog --title "Agreement" \
  --backtitle "Mocis.sh" \
  --no-lines \
  --yesno "Are you sure, you want to install NFS (Network Storage System)?" 0 0
  response=$?
          case $response in
          0) echo "starting";;
          1)bash $Home;;
          255) clear echo "[ESC] key pressed.";;
      esac
        if [ $response = 0 ]
        then
          nfs_server start_nfs_server
          goback=1
        fi
fi
if [[ $omv = 1 ]]; then
  dialog --title "Agreement" \
  --backtitle "Mocis.sh" \
  --no-lines \
  --yesno "Are you sure, you want to install OpenMediaVault?" 0 0
  response=$?
          case $response in
          0) echo "starting";;
          1)bash $Home;;
          255) clear echo "[ESC] key pressed.";;
      esac
        if [ $response = 0 ]
        then
          F_openmediavault start_openmedia
          goback=1
        fi
fi
if [ $nginx = 1 ] ; then
  apt-get install nginx -y > /dev/null
  nginxversion=$(nginx -v)
  dialog --no-lines --backtitle "[ M.O.C.I.S ]" --title "Nginx Version" --msgbox "Check Nginx Version\n\n$nginxversion" 0 0
  bash $Home
fi
if [ $apache2 = 1 ] ; then
  apt-get install apache2 -y > /dev/null
  apache2version=$(apache2 -v)
  dialog --no-lines --backtitle "[ M.O.C.I.S ]" --title "Apache Version" --msgbox "Check Apache2 Version\n\n$apache2version" 0 0
  bash $Home
fi
if [ $mysql = 1 ] ; then
  clear
  echo "Please wait installing in background\nThis can take some time"
  apt-get install mysql-server -y > /dev/null
  mysql_secure_installation
  clear
  mysqlversion=$(mysql --version)
  dialog --no-lines --backtitle "[ M.O.C.I.S ]" --title "MySQL Version" --msgbox "Check MySQL Version\n\n$mysqlversion" 0 0
  bash $Home
fi
if [ $mariadb = 1 ] ; then
    F_mariadb start_mariadb
    mariadbversion=$(mariadb --version)
    dialog --no-lines --backtitle "[ M.O.C.I.S ]" --title "MariaDB Version" --msgbox "Check MaraiDB Version\n\n$mariadbversion" 0 0
    goback=1
fi
if [ $lamp_interactive = 1 ] ; then
bash $Path/repo/apt/lamp_interactive.sh
fi
if [ $openvpn = 1 ] ; then
bash $Path/repo/uni/openvpn-install
fi
if [ $goback = 1 ] ; then
bash $Home
exit
fi
trap "rm $INPUT; exit" SIGHUP SIGINT SIGTERM
