#!/bin/bash
############################################################
# Developed by Store-Host
# Version 0.0.5.0
# Web: https://www.store-host.com
#       Store-Host is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
############################################################
############################################################
#   Loading the Setup variables                            #
############################################################
source /usr/share/mocis/sys/config/setup-vars
############################################################
#   loading installation functions                         #
############################################################
source $Path/repo/apt/9/installation
############################################################
#   Dialog for all Installations                           #
############################################################
phpmyadmin=0
webmin=0
nextcloud=0
easywi=0
goback=0
sinusbot=0
INPUT=save.$$
trap "rm $INPUT; exit" SIGHUP SIGINT SIGTERM
dialog --clear --backtitle "[ M.O.C.I.S ]" \
--title "[ Server Webinterfaces ]" \
--no-lines \
--menu "You can use the UP/DOWN arrow keys, the first \n\
letter of the choice as a hot key, or the \n\
number keys 1-9 to choose an option.\n\
Choose the TASK" 0 0 8 \
Easy-Wi "Gameserver Webinterface" \
Webmin "System management" \
Nextcloud "Online Cloud" \
PHPmyAdmin "MySQL Webaccess" \
Sinusbot "Teamspeak Musicbot" \
Back "Back to the Mainmenu" \
Exit "Exit to the shell" 2>"${INPUT}"
menuitem=$(<"${INPUT}")
[ -f $INPUT ] && rm $INPUT
# make decision
case $menuitem in
        PHPmyAdmin) phpmyadmin=1;;
        Webmin) webmin=1;;
        Nextcloud) nextcloud=1;;
		    Easy-Wi) easywi=1;;
        Back) goback=1;;
        Sinusbot) sinusbot=1;;
        Exit) echo "Bye"; break;;
esac

if [ $phpmyadmin = 1 ] ; then
	apt-get install phpmyadmin -y
fi
if [[ $webmin = 1 ]]; then
  dialog --title "Agreement" \
  --backtitle "Mocis.sh" \
  --no-lines \
  --yesno "Are you sure, you want to install Webmin (Online system overview)?" 0 0
  response=$?
          case $response in
          0) echo "starting";;
          1)bash $Home;;
          255) clear echo "[ESC] key pressed.";;
      esac
        if [ $response = 0 ]
        then
          F_webmin start_webmin
          goback=1
        fi
fi
if [[ $nextcloud = 1 ]]; then
  dialog --title "Agreement" \
  --backtitle "Mocis.sh" \
  --no-lines \
  --yesno "Are you sure, you want to install Nextcloud (Online Cloud Storage)?" 0 0
  response=$?
          case $response in
          0) echo "starting";;
          1)bash $Home;;
          255) clear echo "[ESC] key pressed.";;
      esac
        if [ $response = 0 ]
        then
          F_nextcloud start_netxtcloud
          goback=1
        fi
fi
if [ $easywi = 1 ] ; then
				dialog --yesno "This can damage your system !! Do you want to continue?" 0 0
                response=$?
                case $response in
                0) echo "Starting";;
                1) echo exit;;
                255) echo "[ESC] key pressed.";;
                esac
                        if [ $response = 0 ]
                        then
							echo "Easy web interface is prepared."
							wget https://raw.githubusercontent.com/easy-wi/installer/master/easy-wi_install.sh /usr/share/mocis/repo/apt/
              bash $Path/repo/apt/easy-wi_install.sh
              bash $Home
						fi
fi
if [ $goback = 1 ] ; then
	bash $Home
fi
if [ $sinusbot = 1 ] ; then
	perl $Path/repo/apt/sinusbot.pl
fi
