#!/bin/bash
############################################################
# Developed by Store-Host
# Version 0.0.5.0
# Web: https://www.store-host.com
#       Store-Host is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
############################################################
. /usr/share/mocis/sys/config/setup-vars
goback=0
sslperl=0
teampass=0
INPUT=save.$$
trap "rm $INPUT; exit" SIGHUP SIGINT SIGTERM
dialog --clear --backtitle "[ M.O.C.I.S ]" \
--title "[ #Security ]" \
--no-lines \
--menu "Here you can Install an SSL certificate or later some tools.\n" 0 0 8 \
SSL "Let's Encrypt whit certbot" \
TeamPass "Password Management" \
Back "Back to the Mainmenu" \
Exit "Exit to the shell" 2>"${INPUT}"
menuitem=$(<"${INPUT}")
[ -f $INPUT ] && rm $INPUT
case $menuitem in
        SSL) sslperl=1;;
        TeamPass) teampass=1;;
        Back) goback=1;;
        Exit) echo "Bye"; clear;
esac
if [ $sslperl = 1 ] ; then
	perl $Path/repo/apt/9/letsencrypt.deb.pl
  bash $Home
fi
if [ teampass = 1 ]; then
  if ! which nginx > /dev/null 2>&1; then
      echo "Nginx is not supported. Please install Apache2"
      exit
  fi
else
  echo "Perfect... Nginx not installed"
fi
if ! which apache2 > /dev/null 2>&1; then
  apt-get install apache2 -y > /dev/null
fi
if ! which mysql > /dev/null 2>&1; then
  echo "installing Mysql Server"
  apt-get install mariadb-server -y > /dev/null
  mysql_secure_installation
else
  echo "MySQL is Installed continue whit installation"
fi
apt-get install php7.0 php7.0-ldap php7.0-mysql php7.0-mcrypt php7.0-mbstring php7.0-fpm php7.0-common php7.0-xml php7.0-gd openssl php7.0-mysql php7.0-curl php7.0-bcmath -y > /dev/null
service apache2 restart
if ! which phpmyadmin > /dev/null 2>&1; then
    echo "PHPmyAdmin is not installed"
    apt-get install phpmyadmin -y
    dialog --no-lines \
    --title "M.O.C.I.S" \
    --msgbox  "Please navigate to your PHPmyAdmin.\n.There create a new Database and User." 0 0
    apt-get install zip -y > /dev/null
    wget --no-check-certificate https://github.com/nilsteampassnet/TeamPass/archive/master.zip &>/dev/null
    unzip master.zip
    rm master.zip
    mv TeamPass-master/ /var/www/html/teampass
    chmod -R 0777 /var/www/html/teampass/includes/config
    chmod -R 0777 /var/www/html/teampass/includes/avatars
    chmod -R 0777 /var/www/html/teampass/includes/libraries/csrfp/libs
    chmod -R 0777 /var/www/html/teampass/includes/libraries/csrfp/log
    chmod -R 0777 /var/www/html/teampass/includes/libraries/csrfp/js
    chmod -R 0777 /var/www/html/teampass/backups
    chmod -R 0777 /var/www/html/teampass/files
    chmod -R 0777 /var/www/html/teampass/includes
    chmod -R 0777 /var/www/html/teampass/install
    chmod -R 0777 /var/www/html/teampass/upload
    dialog --no-lines \
    --title "M.O.C.I.S" \
    --msgbox  "You can now navigate to: yourip/teampass." 0 0
    sleep 10
    bash $Home
fi
  bash $Home
fi
if [ $goback = 1 ] ; then
	bash $Home
fi
