#!/bin/bash
############################################################
# Developed by Store-Host
# Version 0.0.5.0
# Web: https://www.store-host.com
#       Store-Host is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
############################################################
#   Loading the Setup variables                            #
############################################################
source /usr/share/mocis/sys/config/setup-vars
############################################################
#   loading installation functions                         #
############################################################
source $Path/repo/apt/9/installation
############################################################
#   Dialog for all Installations                           #
############################################################
goback=0
sslperl=0
teampass=0
INPUT=save.$$
trap "rm $INPUT; exit" SIGHUP SIGINT SIGTERM
dialog --clear --backtitle "[ M.O.C.I.S ]" \
--title "[ #Security ]" \
--no-lines \
--menu "Here you can Install an SSL certificate or later some tools.\n" 0 0 8 \
SSL "Let's Encrypt whit certbot" \
TeamPass "Password Management" \
Back "Back to the Mainmenu" \
Exit "Exit to the shell" 2>"${INPUT}"
menuitem=$(<"${INPUT}")
[ -f $INPUT ] && rm $INPUT
case $menuitem in
        SSL) sslperl=1;;
        TeamPass) teampass=1;;
        Back) goback=1;;
        Exit) echo "Bye"; clear;
esac
if [ $sslperl = 1 ] ; then
	perl $Path/repo/apt/9/letsencrypt.deb.pl
  bash $Home
fi
if [ $teampass = 1 ]; then
  dialog --title "Agreement" \
  --backtitle "Mocis.sh" \
  --no-lines \
  --yesno "Are you sure, you want to install Teampass Online Password Storage?  " 0 0
  response=$?
          case $response in
          0) echo "starting";;
          1) bash $Home;;
          255) clear echo "[ESC] key pressed.";;
  		esac
  			if [ $response = 0 ]
  			then
          F_teampass start_teampass
          goback=1
        fi
fi

if [ $goback = 1 ] ; then
	bash $Home
fi
