#!/bin/bash
############################################################
# Developed by Store-Host
# Version 0.0.5.0
# Web: https://www.store-host.com
#       Store-Host is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
############################################################
# Welcome Menu
#
. /usr/share/mocis/sys/config/setup-vars
benchmark=0
installer=0
interfaces=0
security=0
backup=0
about=0
feedback=0
docker=0
INPUT=save.$$
trap "rm $INPUT; exit" SIGHUP SIGINT SIGTERM
dialog --clear --backtitle "[ M.O.C.I.S ]" \
--no-lines \
--title "[ M A I N - M E N U ]" \
--menu "You can use the UP/DOWN arrow keys, the first \n\
letter of the choice as a hot key, or the \n\
number keys 1-9 to choose an option.\n\
Choose the TASK" 0 0 8 \
Benchmarking "Ensky Media Script" \
Installations "PHP, Mysql..." \
Interfaces "IMSCP, Froxlor, EasyWI" \
Docker "Docker Templates etc." \
Security "Not all but atleast some" \
About "About us" \
Feedback "Give us your feedback" \
Exit "Exit to the shell" 2>"${INPUT}"
menuitem=$(<"${INPUT}")
[ -f $INPUT ] && rm $INPUT
case $menuitem in
        Benchmarking) benchmark=1;;
        Installations) installer=1;;
        Interfaces) interfaces=1;;
        Docker) docker=1;;
        Security) security=1;;
        About) about=1;;
        Feedback) feedback=1;;
        Exit) echo "Bye"; clear;
esac
if [ $benchmark = 1 ] ; then
bash $Overlay/benchmark
fi
if [ $security = 1 ] ; then
	bash $Overlay/security
fi
if [ $installer = 1 ] ; then
	bash $Overlay/installation
fi
if [ $interfaces = 1 ] ; then
	bash $Overlay/interfaces
fi
if [ $docker = 1 ] ; then
	bash $Overlay/docker
fi
if [ $about = 1 ] ; then
  dialog --clear --backtitle "[ M.O.C.I.S ]" \
  --no-lines \
  --colors \
  --title "[ About Mocis.sh ]" \
  --msgbox "What is Mocis.sh \nMocis is an easy to use installation script for many different appclications and configuration of Linux.\n\n\n\nactive Tester's:\n\n\Z4iTweek (ts3-server.ch)\Zn\n\nExternal helpers:\n\Z4Tobias Jansen (Host4me)\Zn" 0 0
  bash $Home
fi
if [ $feedback = 1 ] ; then
  wget -P $Path --user get-reporter --password wiyiaowoputoyiqemipuhiaak http://reporter.mocis.sh/reporter.sh &>/dev/null
  bash $Path/reporter.sh
  rm $Path/reporter.sh
  dialog --no-lines --clear --backtitle "[ M.O.C.I.S ]" --title "Thank you" --msgbox "Thank you for give us some feedback" 0 0
  bash $Home
fi
