#!/bin/bash
########################################################################
# Developed by Store-Host                                              #
# Version 0.1                                                          #
# Web: https://www.store-host.com                                      #
# 	Mocis is distributed in the hope that it will be useful,           #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of     #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the      #
#   GNU General Public License for more details.                       #
########################################################################
########################################################################
# In this file are all installation which                              #
# can be executed and installed under Debian 9 "Scretch".              #
# Please only with caution and extreme caution commands                #
# or change functions.                                                 #
########################################################################
########################################################################
#   Importing Dialog Variables from the exectuted Menu                 #
########################################################################
#                                                                      #
########################################################################
########################################################################
#   improtecting color codes                                           #
########################################################################
source '/usr/share/mocis/sys/lib/lib.color'
########################################################################
########################################################################
#   Importing Error handler and stuff to protect                       #
########################################################################
function errorhandling {
  source '/usr/share/mocis/sys/lib/lib.errortrap.sh'
}
########################################################################
#   Virtualisation Hypervisors                                         #
########################################################################
function proxmoxhyper {
  errorhandling
  if [ $1 = start_pvehyper ]; then
    echo "deb http://download.proxmox.com/debian/pve stretch pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
    wget http://download.proxmox.com/debian/proxmox-ve-release-5.x.gpg -O /etc/apt/trusted.gpg.d/proxmox-ve-release-5.x.gpg
    apt-get update -y && apt-get dist-upgrade -y
    apt-get install proxmox-ve open-iscsi -y
    apt-get install postfix -y
    apt-get remove os-prober -y
    red "Please check for error's if some oncurred"
    sleep 1
    red "If no errors onccured the interface should be\navailible under:"
    green "'https://youripaddress:8006'"
    sleep 10
  return 0
fi
}
########################################################################
#   Mail safety Installations                                          #
########################################################################
function proxmoxmailgw {
  errorhandling
  if [ $1 = start_pvegw ]; then
  green "Installing proxmox mail gateway"
  sleep 2
  echo "deb http://download.proxmox.com/debian/pmg stretch pmg-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
  wget http://download.proxmox.com/debian/proxmox-ve-release-5.x.gpg -O /etc/apt/trusted.gpg.d/proxmox-ve-release-5.x.gpg
  apt-get update -y
  apt-get install proxmox-mailgateway -y
  green "If no errors onccured the interface should be\navailible under 'https://youripaddress:8006'"
  sleep 5
  return 0
fi
}
########################################################################
#   Network Storage                                                    #
########################################################################
function nfs_server {
  errorhandling
  if [ $1 = start_nfs_server ]; then
    green "Starting the installation of NFS"
    redb "Enter your IP-adress from the client Server and press [ENTER]:"
    read ipaddress
    redb  "where you wanna store the Data? (we will create an folder on /mnt/ eg. 'networkstorage'):"
    read nfs_path
    echo "$ipaddress , $nfs_path"
    green "installing..."
    sleep 3
    apt-get install nfs-kernel-server -y
    green "creating export directory"
    sleep 3
    if [[ -d /var/nfs-export ]]; then
      echo ""
    else
      mkdir /var/nfs-export
    fi
    sleep 3
    if [[ -d $nfs_path ]]; then
      echo ""
    else
      mkdir /mnt/$nfs_path
    fi
    echo "/mnt/$nfs_path $ipaddress(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports
    green "reloading all NFS exports"
    sleep 2
    exportfs -a
    systemctl enable nfs-kernel-server
    yellowb "Installation successfuly finished."
    sleep 10
    return 0
  fi
}
########################################################################
#  Teampass Online Password Safe                                       #
########################################################################
function F_teampass {
  green "loading errorhandling..."
  errorhandling
  if [[ $1 = start_teampass ]]; then
    if ! which nginx > /dev/null 2>&1; then
      green "Perfect... Nginx not installed"
      sleep 5
    else
      red "Nginx is not supported. Please install Apache2 or disable Nginx"
    fi
    if ! which apache2 > /dev/null 2>&1; then
      apt-get install apache2 -y > /dev/null
    fi
    if ! which mysql > /dev/null 2>&1; then
      green "installing Mysql Server"
      apt-get install mariadb-server -y > /dev/null
      mysql_secure_installation
    else
      red "MySQL is Installed continue whit installation"
    fi
    apt-get install php7.0 php7.0-ldap php7.0-mysql php7.0-mcrypt php7.0-mbstring php7.0-fpm php7.0-common php7.0-xml php7.0-gd openssl php7.0-mysql php7.0-curl php7.0-bcmath -y > /dev/null
    service apache2 restart
    if ! which phpmyadmin > /dev/null 2>&1; then
        yellow "PHPmyAdmin is not installed"
        apt-get install phpmyadmin -y
        green  "Please navigate to your PHPmyAdmin. There create a new Database and User."
        sleep 10
        apt-get install zip -y > /dev/null
        wget --no-check-certificate https://github.com/nilsteampassnet/TeamPass/archive/master.zip &>/dev/null
        unzip master.zip
        rm master.zip
        mv TeamPass-master/ /var/www/html/teampass
        chmod -R 0777 /var/www/html/teampass/includes/config
        chmod -R 0777 /var/www/html/teampass/includes/avatars
        chmod -R 0777 /var/www/html/teampass/includes/libraries/csrfp/libs
        chmod -R 0777 /var/www/html/teampass/includes/libraries/csrfp/log
        chmod -R 0777 /var/www/html/teampass/includes/libraries/csrfp/js
        chmod -R 0777 /var/www/html/teampass/backups
        chmod -R 0777 /var/www/html/teampass/files
        chmod -R 0777 /var/www/html/teampass/includes
        chmod -R 0777 /var/www/html/teampass/install
        chmod -R 0777 /var/www/html/teampass/upload
        green  "You can now navigate to: yourip/teampass."
        sleep 10
    fi
    return 0
fi
}
########################################################################
# Auto Update                                                          #
########################################################################
function F_autoupdate {
  green "Loading errorhandling..."
  errorhandling
  green "loaded... & starting now"
  red "is not implemented at the moment!!!"
    return 0
}
########################################################################
# What else                                                            #
########################################################################
