#!/bin/bash
############################################################
# Developed by Store-Host
# Version 0.0.5.0
# Web: https://www.store-host.com
#	Store-Host is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
############################################################
# Vars
#
. /usr/share/mocis/sys/config/setup-vars
#source '/usr/share/mocis/sys/lib/lib.errortrap.sh'
function finish {
  clear
  bash $Home
}
dialog --title "Last chance" \
--backtitle "Mocis.sh" \
--no-lines \
--yesno "Are you sure you want to install Proxmox VE?" 0 0
response=$?
        case $response in
        0) echo "";;
        1) clear exit;;
        255) clear echo "[ESC] key pressed.";;
		esac
			if [ $response = 0 ]
			then
				echo "deb http://download.proxmox.com/debian/pve stretch pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
        wget http://download.proxmox.com/debian/proxmox-ve-release-5.x.gpg -O /etc/apt/trusted.gpg.d/proxmox-ve-release-5.x.gpg
        apt-get update -y && apt-get dist-upgrade -y
        apt-get install proxmox-ve open-iscsi -y
        apt-get install postfix -y
        dialog --title "OS Prober" \
        --backtitle "Mocis.sh" \
        --no-lines \
        --yesno "Recommended: remove the os-prober package \nThe os-prober package scans all the partitions of your host including those of you guests VMs to create dual-boot GRUB entries. If you didn't install Proxmox VE as a dual boot besides another Operating System you can safely remove the os-prober package." 0 0
        response=$?
                case $response in
                0) echo "";;
                1) clear ;;
                255) clear echo "[ESC] key pressed.";;
        		esac
        			if [ $response = 0 ];
              then
                apt-get remove os-prober -y
              else
                echo ""
              fi
              dialog --title "Restarting the Server" \
              --backtitle "Mocis.sh" \
              --no-lines \
              --yesno "We would like to point out that you should now restart the server. Would you like us to do this for you??" 0 0
              response=$?
                      case $response in
                      0) echo "";;
                      1) clear ;;
                      255) clear echo "[ESC] key pressed.";;
              		esac
              			if [ $response = 0 ];
              			then
                      shutdown -r -t 1
                    else
                    echo ""
                    fi
fi
echo "Please check for error's if some oncurred"
sleep 1
trap finish EXIT
